package randomnumberguessing;
import java.util.Scanner;
public class guessRandomNumber {
	public static void randomnumbergame() {
		Scanner sc=new Scanner(System.in);
		int number=1+(int)(30* Math.random());
		int k=5;
		System.out.println("A Random number between 1 to 30 has been generated by the computer guess the number");
		System.out.println("you are left over with "+k+" attempts");
		for(int i=0;i<k;i++) {
			System.out.print("enter the number : ");
			int guess=sc.nextInt();
			if(guess==number) {
				System.out.println("congratulations its a correct guess");
				sc.close();
				return;
			}
			else if(guess>number) {
				System.out.println("your guess is higher than the random number");
				System.out.println("your are left over with "+(k-1)+" attempts");
			}
			else {
				System.out.println("your guess is lower than the random number");
				System.out.println("your are left over with "+(k-1)+" attempts");
			}
		}
		System.out.println("you have used all your attempts");
		sc.close();
	}

	public static void main(String[] args) {
		randomnumbergame();
	}

}
